name: "Run kurento-buildpackage"

on:
  # Triggered manually.
  workflow_dispatch:
    inputs:
      jobDistros:
        description: "List of Ubuntu codenames to build for"
        required: true
        # There is no `list` type, so use a raw JSON array and `fromJson()`.
        # Example: '["xenial", "bionic", "focal"]'
        type: "string"
        default: '["focal"]'
      jobGitName:
        description: "Non-default git branch or tag that should be checked out, if it exists"
        required: false
        type: "string"
        default: "7.0.0"
      jobGitNameFallback:
        description: "Non-default git branch or tag that should be checked out, if `jobGitName` does not exist"
        required: false
        type: "string"
        default: ""
      jobRelease:
        description: "Enable to build release versions; disable for development builds"
        required: false
        type: "boolean"
        default: false

jobs:
  libsrtp:
    uses: "./.github/workflows/kurento-buildpackage.reusable.yaml"
    with:
      jobDistros: "${{ inputs.jobDistros }}"
      jobGitName: "${{ inputs.jobGitName }}"
      jobGitNameFallback: "${{ inputs.jobGitNameFallback }}"
      jobRelease: ${{ inputs.jobRelease }}
